[package]
name = "schoolduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.5"
rand = "0.8.4"
rayon = "1.5.1"
num = "0.4.0"